set -sg escape-time 50

# set windows' look
set-option -g window-status-format "[#I:#W#F]"
set-option -g window-status-current-format "#[bg=cyan,fg=black][#I:#W#F]"

setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"

set -g set-clipboard on
