corner-radius = 15

blur:
{
  method = "dual_kawase";
  size = 10;
  strength = 5;
};

no-fading-openclose = true;

rules = (
        { match = "focused"; opacity = 0.95; },
        { match = "!focused"; opacity = 0.85; },
        { match = "name *?= \"chrome\""; opacity = 1; },
        { match = "class_g *?= \"Slock\""; blur-background = false; opacity = 1; },
        # ... and so on
)
